# Generated by Django 2.2.2 on 2019-06-14 15:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('money', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Format is +111111111111111. Max 15 digits is allowed.', regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('added_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], default='l', max_length=20)),
                ('flavours', models.ManyToManyField(to='api_v1.Flavour')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('init', 'Initial'), ('paid', 'Paid'), ('on_the_way', 'On the way'), ('delivered', 'Delivered')], default='init', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.Customer')),
                ('pizzas', models.ManyToManyField(to='api_v1.Pizza')),
            ],
        ),
    ]
