# Generated by Django 2.2.2 on 2019-06-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_sum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('init', 'Initial'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='init', max_length=20),
        ),
    ]
